services:
  - type: web
    name: questsave-api
    runtime: docker
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: YTDLP_PATH
        value: yt-dlp
      - key: YTDLP_IMPERSONATE
        value: chrome
      - key: YTDLP_TIMEOUT_MS
        value: "180000"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: MAIL_FROM_NAME
        value: QuestSave
      - key: MAIL_FROM_EMAIL
        value: noreply@questlabs.cc
      - key: YTDLP_COOKIES
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: RAPIDAPI_YOUTUBE_HOST
        value: ytstream-download-youtube-videos.p.rapidapi.com
      - key: RAPIDAPI_INSTAGRAM_HOST
        value: instagram-post-reels-stories-downloader-api.p.rapidapi.com
      - key: RAPIDAPI_FACEBOOK_HOST
        value: new-facebook-downloader-reels-watch-share-links.p.rapidapi.com
